import = [ "~/.config/alacritty/themes/themes/solarized_osaka.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window.padding]
x = 20
y = 5
