import = [
	"~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "FiraCode Nerd Font"
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "FiraCode Nerd Font"
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "FiraCode Nerd Font"
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
# family = "FiraCode Nerd Font"
family = "Iosevka Nerd Font"
style = "Regular"

[window.padding]
x = 20
y = 5
